apiVersion: v1
kind: Secret
metadata:
  name: budget-secret
  labels:
    app: budget-ws
    tier: backend
type: Opaque
data:
  spring.datasource.username: "cG9zdGdyZXM="
  spring.datasource.password: "cm9vdA=="


# To apply this secret's file run kubectl apply -f budget-secret.yaml
# To find the secret's list run kubectl get secrets
# To check the created secrets run kubectl describe secret budget-secret
# To check the volume run kubectl exec -it <pod-name> -c budget-ws-container -- /bin/sh